language: cpp
dist: bionic
sudo: required

env:
  global:
    - FLAGS="-DWITH_QT5=ON -DWITH_ALSA=ON -DWITH_GSM=ON -DWITH_SPEEX=ON -DWITH_ZRTP=OFF"
    # (qttools5-dev-tools is explicitly included because of Debian bug #835295)
    - PACKAGES="libasound2-dev libgsm1-dev libspeex-dev libspeexdsp-dev qtdeclarative5-dev qttools5-dev qttools5-dev-tools"

  matrix:
    # Test various compiler versions
    - PACKAGES_ADD="g++-5"     MATRIX_EVAL="CC=gcc-5     && CXX=g++-5"
    - PACKAGES_ADD="g++-6"     MATRIX_EVAL="CC=gcc-6     && CXX=g++-6"
    - PACKAGES_ADD="g++-7"     MATRIX_EVAL="CC=gcc-7     && CXX=g++-7"
    - PACKAGES_ADD="g++-8"     MATRIX_EVAL="CC=gcc-8     && CXX=g++-8"
    - PACKAGES_ADD="g++-9"     MATRIX_EVAL="CC=gcc-9     && CXX=g++-9"
    - PACKAGES_ADD="clang-3.9" MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
    - PACKAGES_ADD="clang-4.0" MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
    - PACKAGES_ADD="clang-5.0" MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    - PACKAGES_ADD="clang-6.0" MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
    - PACKAGES_ADD="clang-7"   MATRIX_EVAL="CC=clang-7   && CXX=clang++-7"
    - PACKAGES_ADD="clang-8"   MATRIX_EVAL="CC=clang-8   && CXX=clang++-8"

    # Test with all options disabled
    - FLAGS="-DWITH_QT5=OFF -DWITH_ALSA=OFF -DWITH_GSM=OFF -DWITH_SPEEX=OFF -DWITH_ZRTP=OFF" PACKAGES=""

    # Test building with bcg729
    - BUILD_BCG729="master" FLAGS="-DWITH_QT5=OFF -DWITH_ALSA=OFF -DWITH_G729=ON" PACKAGES="git ca-certificates"
    # Also test the old pre-1.0.2 API (see issue #104)
    - BUILD_BCG729="1.0.1" BUILD_BCG729_AUTOTOOLS="Y" FLAGS="-DWITH_QT5=OFF -DWITH_ALSA=OFF -DWITH_G729=ON" PACKAGES="git ca-certificates pkg-config libtool automake autoconf"

# See https://docs.travis-ci.com/user/languages/cpp/#C11-C%2B%2B11-%28and-Beyond%29-and-Toolchain-Versioning
before_install:
  - eval "${MATRIX_EVAL}"

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get -y install bison cmake flex libccrtp-dev libmagic-dev libreadline-dev libsndfile1-dev libucommon-dev libxml2-dev linux-libc-dev $PACKAGES $PACKAGES_ADD

script:
  # Download and build bcg729 if necessary
  - if [ "$BUILD_BCG729" ]; then git clone git://git.linphone.org/bcg729.git --branch "$BUILD_BCG729" && (cd bcg729 && if [ "$BUILD_BCG729_AUTOTOOLS" ]; then ./autogen.sh && ./configure; else cmake .; fi && make && sudo make install); fi
  - mkdir _build
  - cd _build
  - cmake -DCMAKE_INSTALL_PREFIX=../_install $FLAGS ..
  - cmake --build . --target install
